language: node_js
node_js:
- '6'
before_script:
- npm install
script:
- npm run test
- npm run build
deploy:
  provider: npm
  email: henry.seres@gmail.com
  api_key:
    secure: W3fu9ztU/WShocJ+XknaJw2bBYUXx7QeCVPucA4Zg9BwjO8NwgwerztihvyPC4B7eFNPtKmP3sGYWh69LRcWkq0OGmSgBr3l44U7SuD56PYgg0hSHqfaGBAfm9YoQV4wsCqMSw/yrMZtuFToDVseTN/MKeY/tMNN3LypVhtU+bylgwMxP5UFxObv83iVgqS00wsKvIGCAy3K5XCISYVvqGz5YiOQ8gZEL3bFpJfXAj6r7k3mhV8/QgkSsu650gH6UngKMRD/H2OlHW/owcePZGzA9gWpVn6KiOvQj/11jFqKV6jSWEga7gYLcNXXPeCoNMbyFI8N8qc0wLm53XXIjvksl9cRQrPtHLdbstVYNqbVfEcNKGzqadhzzADQym8QZ+2twlDDW4N46XcCSbsid4JdP+QKEU0AicmK7Uf0GCqBUD2QufY+39sTMtgbwUSWG9CweM32Zy4NWzkV6At2VnEdSAEAyjbCEj5gcDpMF6RqTLxvMLGNyvYu3c0rc3t8l5XBT6lTFUlqQdE/1NibjaRq0sdWxgzjNTO80TKeLxceE9T55YDwCMCX0uaPJgF2FtJOuIcj9rqRaDzK0+NBLYnv7WMrzSPx6Cg2mFww9sBEqV8ahsb/3FVS9222iMQictoGw5N3Q5u298PNNS5br+XnUfAi8UJtgQqBbaxifls=
  on:
    branch: master
cache: yarn
notifications:
  email: false
